spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DreamsZM/config-repo
          username: 602128569@qq.com
          password: a7078796123
          basedir: G:\JavaProject\project\SpringCloud_Sell\config\basedir
  rabbitmq:
    host: 192.168.1.141
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

